server:
  port: ${PORT:8000}
spring:
  application:
    name: user-api
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}