spring:
    application:
        name: payroll-api
server:
    port: 8100
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
