
spring:
    application:
        name: api-gateway
server:
    port: ${PORT:8765}
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}